# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 1d062c94f87003dd375df72bd54f29b451c07584217c15b7c029778f507d5511cb66f0de00c516925c3688b9a552888c09cf86b02551f58daf1181b37c8cfcb8
  secret_api_key: my_secret

test:
  secret_key_base: 8e83b8e5bcd4c4fc8b44e9bf49e5d30c5d98938a4e14866a0ca173ea501a703302e4d1bf09b9c52a6533e549cf8f2149f3153f2e6b4b5b615a9a721b83980c79
  secret_api_key: my_secret

# Do not keep production secrets in the repository,
# instead read values from the environment.
integration:
  secret_key_base: <%= Figaro.env.SECRET_KEY_BASE %>
  secret_api_key: <%= Figaro.env.SECRET_API_KEY %>

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= Figaro.env.SECRET_KEY_BASE %>
  secret_api_key: <%= Figaro.env.SECRET_API_KEY %>
